site_name: Bergwerk Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - Running Multiple Instances: multiple_instances.md


  - Containers:
    - Docker Compose: containers/compose.md
    - Bergwerk Wiki: containers/bergwerk-wiki.md
    - Bergwerk Api: containers/bergwerk-api.md
    - Bergwerk Database: containers/bergwerk-db.md
    - Bergwerk Cron: containers/bergwerk-cron.md
    - Bergwerk Socketio: containers/bergwerk-socketio.md
    - Bergwerk Caddy: containers/bergwerk-caddy.md
  - Authors: authors.md
  - License: license.md

theme: material

plugins:
  - mkdocstrings
  - search
  - snippets

markdown_extensions:
    - pymdownx.snippets:

